version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: funtime-docker
    restart: always
    ports:
      - 8004:80
#    volumes:
#      - .:/srv/app
# if uncomment upper it gives us 403... it should enable possibility for changing code in runtime and be effectively seen in docker image
